version: "3"

services: 
  postgresdb:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=dev_db
  
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev   

volumes:
  postgres_data:

