# Generated by Django 3.2.6 on 2021-08-29 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import file_sharing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('docfile', models.FileField(upload_to=file_sharing.models.user_directory_path, verbose_name='Docfile')),
                ('daysOfvalidity', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(1)], verbose_name='DaysOfvalidity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
