# Generated by Django 3.2.7 on 2021-09-09 18:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file_sharing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('docfile', models.FileField(upload_to=file_sharing.models.user_directory_path, verbose_name='Docfile')),
                ('created_at', models.DateField(auto_now_add=True, db_index=True, verbose_name='Created_at')),
                ('end_at', models.DateTimeField(default=datetime.datetime(2021, 10, 9, 18, 7, 41, 382890), verbose_name='End_at')),
                ('countOfdownloads', models.IntegerField(default=0, editable=False, verbose_name='CountOfdownloads')),
                ('in_archive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
