# Generated by Django 3.2.7 on 2021-09-10 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='file',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 9, 16, 44, 892000), verbose_name='End_at'),
        ),
    ]
